/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

/**
 *
 * @author Dell
 */
public class Inventario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Inventario.class.getName());

    /**
     * Creates new form Inventario
     */
    public Inventario() {
        initComponents();
     this.setSize(940, 415); 
    this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Venta = new javax.swing.JButton();
        btn_Estadisticas = new javax.swing.JButton();
        btn_Inventario = new javax.swing.JButton();
        btn_Perfil = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();
        item_listado = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setMaximumSize(new java.awt.Dimension(940, 390));
        setPreferredSize(new java.awt.Dimension(490, 390));
        setResizable(false);

        btn_Venta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Venta.setText("Ventas");
        btn_Venta.setFocusable(false);
        btn_Venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VentaActionPerformed(evt);
            }
        });

        btn_Estadisticas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Estadisticas.setText("Estadistica");
        btn_Estadisticas.setFocusable(false);
        btn_Estadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EstadisticasActionPerformed(evt);
            }
        });

        btn_Inventario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Inventario.setText("Inventario");
        btn_Inventario.setFocusable(false);
        btn_Inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InventarioActionPerformed(evt);
            }
        });

        btn_Perfil.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Perfil.setText("Perfil");
        btn_Perfil.setFocusable(false);

        btn_Salir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Salir.setText("Salir");
        btn_Salir.setFocusable(false);
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        item_listado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        item_listado.setMaximumRowCount(20);
        item_listado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una categoría...", "Productos para el hogar", "Electrodomesticos", "Productos Limpieza", "Alimentos y Abarrotes", "Cuidado Personal", "Tecnología y Electrónica" }));
        item_listado.setToolTipText("");
        item_listado.setFocusable(false);
        item_listado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_listadoActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Tipo", "Precio", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Estadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Venta, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(item_listado, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Venta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btn_Estadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btn_Inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btn_Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(item_listado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_VentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VentaActionPerformed

        // Creamos la ventana de Ventas
        Ventas Product = new Ventas();
        // La hacemos visible en pantalla
        Product.setVisible(true);
        // Cerramos la ventana de Inventario actual para liberar memoria
        this.dispose();
        
    }//GEN-LAST:event_btn_VentaActionPerformed

    private void btn_EstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EstadisticasActionPerformed
        // TODO add your handling code here:

        Estadistica Registro = new Estadistica();
        Registro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_EstadisticasActionPerformed

    private void btn_InventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InventarioActionPerformed
        // TODO add your handling code here:

        Inventario Almacen= new Inventario();
        Almacen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_InventarioActionPerformed

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed

        // esto hace que vueva al login de nuevo

        login Secion = new login();
        Secion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_SalirActionPerformed

    private void item_listadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_listadoActionPerformed
        // TODO add your handling code here:
        
        // 1. Obtenemos la opción que el usuario seleccionó en formato de Texto (String)
        String opcionSeleccionada = item_listado.getSelectedItem().toString();
        
        // 2. Evaluamos qué opción se eligió para ejecutar el código correspondiente
        switch (opcionSeleccionada) {
            case "Seleccione una categoría..." -> {
            }
                
            case "Productos para el hogar" -> // TODO: Añade aquí el código para mostrar u ordenar los productos de Hogar
                System.out.println("Cargando productos para el hogar...");
                
            case "Electrodomesticos" -> // TODO: Añade aquí el código para Electrodomésticos
                System.out.println("Cargando electrodomésticos...");
                
            case "Productos Limpieza" -> // TODO: Añade aquí el código para Limpieza
                System.out.println("Cargando productos de limpieza...");
                
            case "Alimentos y Abarrotes" -> // TODO: Añade aquí el código para Alimentos
                System.out.println("Cargando alimentos y abarrotes...");
                
            case "Cuidado Personal" -> // TODO: Añade aquí el código para Cuidado Personal
                System.out.println("Cargando productos de cuidado personal...");
                
            case "Tecnología y Electrónica" -> // TODO: Añade aquí el código para Tecnología
                System.out.println("Cargando tecnología...");
        }
        // Aquí puedes limpiar la pantalla o mostrar todos los productos por defecto
                
        
    }//GEN-LAST:event_item_listadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Inventario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Estadisticas;
    private javax.swing.JButton btn_Inventario;
    private javax.swing.JButton btn_Perfil;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JButton btn_Venta;
    private javax.swing.JComboBox<String> item_listado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
